language: go
install: true
sudo: required

if: branch = master

go:
    - 1.13.x

install:
    - export GO111MODULE=on
    - go mod vendor
    - go vet

script:
    - go build
    - go install

notifications:
    email: false
