#!/bin/bash

EXE_NAME=persephone
PIGZ_PATH=/usr/bin/pigz
TAR_FLAGS=-zcvf
OS=`uname -o`

if [ ${OS,,} == "msys" ]; then
    EXE_NAME=persephone.exe
    PIGZ_PATH=/mingw64/bin/pigz
    rsrc -ico=persephone.ico -arch=amd64
fi

if [ -f $PIGZ_PATH ]; then
    TAR_FLAGS="-I pigz -cvf"
else
    NOTAR=true
fi

if test -z `which go`; then
	echo "git couldn't find your Go installation, please make sure it's in your PATH"
	exit 1
fi

go build -o $EXE_NAME -i -v

mv temp/.gitkeep gkt

if ! [ -f config.yml ]; then
    if ! [ ${NOTAR+x} ]; then
        cp config.example.yml config.yml
    fi
else
    mv config.yml config.backup.yml
    cp config.example.yml config.yml
fi

# NOTAR will prevent compressing files
if ! [ ${NOTAR+x} ]; then
    tar $TAR_FLAGS persephone.tar.gz $EXE_NAME temp/ static/ config.yml artists.yml
fi

if ! [ ${NOZIP+x} ]; then
	zip persephone-windows.zip $EXE_NAME temp/ static/**/* config.yml artists.yml
fi

# cleanup
mv gkt temp/.gitkeep

if [ -f config.backup.yml ]; then
    rm config.yml
    mv config.backup.yml config.yml
fi
