#!/bin/bash

EXE_NAME=persephone
PIGZ_PATH=/usr/bin/pigz
TAR_FLAGS=-zcvf
OS=`uname -o`

if [ ${OS,,} == "msys" ]; then
    EXE_NAME=persephone.exe
    PIGZ_PATH=/mingw64/bin/pigz
fi

if [ -f $PIGZ_PATH ]; then
    TAR_FLAGS="-I pigz -cvf"
fi

if test -z `which go`; then
	echo "git couldn't find your Go installation, please make sure it's in your PATH"
	exit 1
fi

if test -z `go vet`; then
    echo "Failed to vet your Go code. Please make the above corrections and try again"
    exit 1
fi

go build -o $EXE_NAME -i -v

mv temp/.gitkeep gkt

if ! [ -f config.json ]; then
    if ! [ ${NOTAR+x} ]; then
        cp config.example.json config.json
    fi
fi

# NOTAR will prevent compressing files
if ! [ ${NOTAR+x} ]; then
    tar $TAR_FLAGS persephone.tar.gz $EXE_NAME temp/ static/ config.json artists.json
fi

mv gkt temp/.gitkeep
