name: Java w/Gradle

on:
    push:
        branches: [ java ]
    pull_request:
        branches: [ java ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup JDK
              uses: actions/setup-java@v1
              with:
                java-version: '14-ea'
                java-package: 'jdk'
            - name: exec pers
              run: chmod +x gradlew
            - name: Build
              run: ./gradlew build
